*SAS PROJECT;
/* checking out the variables and its properties*/

DATA SASPDATA.DEMOGRAPHICVARS;
	SET SASPDATA.PROJECT2_VARIABLES;
RUN;
DATA SASPDATA.DEMOGRAPHICS;
	SET SASPDATA.PROJECT2;
RUN;
PROC SQL;
	SELECT * FROM SASPDATA.DEMOGRAPHICVARS ORDER BY 'varnum';
QUIT;

PROC SQL;
	SELECT Name, LABEL FROM SASPDATA.DEMOGRAPHICVARS ORDER BY 'varnum';
quit;

/* checking out sample data*/
PROC SQL outobs=10;
	SELECT * FROM SASPDATA.DEMOGRAPHICS;
QUIT;

/* Exporting data into CSV Files*/
PROC EXPORT data=saspdata.HOUSING2 
		outfile="/Users/KC/Documents/GitHub/SAS-project/SASP/output/demographics_final.csv" dbms=csv;
		/* path for sas ue
		"/folders/myfolders/output/demographicvars.csv"*/
/* 	PATH FOR COLLEGE SYSTEM
	C:/Users/kchamart/Desktop/SASP/saspoutput/demographics.csv */
run;

PROC EXPORT data=saspdata.Demographics 
		outfile="/Users/KC/Documents/GitHub/SAS-project/SASP/Output/demographics.csv" dbms=csv; 
		*path in college system;
run;

/* subsetting the data to match project frame work needs*/
PROC SQL;
	CREATE TABLE SASPDATA.HOUSING AS(
		SELECT ID /* HOUSEHOLD ID*/
		, PNUM /* PERSON NUMBER*/
		, REGION 
		, HHINC /*HOUSE HOLD INCOME AVERAGE */
		, PEOPL /*NUMBER OF PEOPLE */
		, Q4P5
		, Q215P, Q2P15 /*Armed forces 0 OR 1*/
		, CHLDRN14, CHLDRN17, CHLDRN18, CHLDRN20 /* DEPENDENTS */
		, AGE /*AVERAGE*/
		, CITIZEN
		, Q2P17  /* HIGHEST LEVEL OF SCHOOL OR DEGREE  AVERAGE*/
		, Q2P18 , Q2P20 /* number of years a person has lived in the country AVERAGE*/
		, Q2P14 /* MARITAL STATUS */
		, Q4P7 , Q4P3, Q4P4, Q4P6 /*JOB STATUS AND NUMBER OF JOBS */
		, Q4P9 , Q4P10 /*TYPE OF EMPLOYMENT */
		, Q3P2  /* HOUSE OWNERSHIP*/  
		, RSDNC /*MORE THAN 1 HOME IN WASHINGTON STATE*/
		, Q3P2A 
		, Q3P2B 
		, Q3P3 
		, Q3P4 
		, Q3P5 
		
FROM SASPDATA.DEMOGRAPHICS
WHERE AGE GE 16
);
QUIT;

/* Combining CHLDREN INFORMATION into 1 column as it is repetitive */
DATA SASPDATA.HOUSING1 (DROP=CHLDRN14 CHLDRN17 CHLDRN18 CHLDRN20);
	SET SASPDATA.HOUSING;
	LABEL CHLDRN_LT_20 = '# OF CHILDREN BELOW 20 YEARS';

	IF CHLDRN20 >0 THEN
		CHLDRN_LT_20 =CHLDRN20;
	ELSE IF CHLDRN18 >0 THEN
		CHLDRN_LT_20=CHLDRN18;
	ELSE IF CHLDRN17 >0 THEN
		CHLDRN_LT_20=CHLDRN17;
	ELSE IF CHLDRN14 >=0 THEN
		CHLDRN_LT_20=CHLDRN14;
RUN;

/* SORTING DATA FOR QUICKER PROCESSING*/ 
PROC SORT DATA = SASPDATA.HOUSING1 OUT=SASPDATA.HOUSING1_S;
BY ID PNUM;


/* verifing the data for  missing values*/ 
PROC MEANS DATA = SASPDATA.HOUSING1_S NMISS N MIN MAX Q1 Q3;
RUN;

/* checking the sample values */
PROC PRINT DATA=SASPDATA.HOUSING1_S (OBS=10);
RUN;


/* proc transpose data=SASPDATA.HOUSING1S out=SASPDATA.HOUSING1_TS  */
/* 		prefix=PID_ SUFFIX=_HLE; */
/* 	var Q2P17; */
/* 	id PNUM; */
/* 	by ID; */
/* run; */

/* CONSOLIDATING ALL HOUSEHOLD INFORMATION */ 
PROC SQL;
	CREATE TABLE  SASPDATA.HOUSING2 AS
	SELECT DISTINCT ID
	, REGION
	, PEOPL 
	, HHINC FORMAT=DOLLAR10. /*HOUSE HOLD INCOME AVERAGE */
	, ROUND(AVG(Q2P17)) as AVG_EDU_LVL LABEL="AVG OF HGHST LVL OF SCHL OR DGRE"/* Average ofHIGHEST LEVEL OF SCHOOL OR DEGREE  AVERAGE*/
	, ROUND(AVG(AGE))AS AVG_AGE FORMAT= AgeSeg. LABEL="AVERAGE OF AGES OF PPL IN THE HOUSE HOLD"
	, CHLDRN_LT_20
	, SUM(COALESCE(Q4P5,0)) AS OTHR_INCM_SRC LABEL="INCOME FROM FARM OR BUSINESS"
	, RSDNC /*MORE THAN 1 HOME IN WASHINGTON STATE*/
	, ROUND(AVG(CASE WHEN Q2P20 IS NOT NULL THEN 2004-Q2p20 WHEN Q2P18=1 THEN AGE END)) AS NUM_YEARS_US LABEL="AVG NUM OF YRS PPL LIVING IN US"
	, sum(CASE WHEN Q215P=1 OR Q2P15=1 THEN 1 WHEN Q215P=0 and Q2P15=0 THEN 0 else . END) AS NUM_IN_ARMY LABEL="SUM OF PPL SERVING IN THE ARMY"
	, SUM(CASE WHEN Q4P7 IS NOT NULL THEN Q4P7 ELSE 0 END +
	CASE WHEN Q4P4 =1 THEN 1 ELSE 0 END +
	CASE WHEN (Q4P3 = 0 AND Q4P6 IN(4,6,1,16,18)) THEN 1 ELSE 0 END) AS TOTAL_NUM_JOBS_HHLD LABEL="TOTAL NUM OF PPL SERVING IN ARMY"
	, (CASE WHEN MAX(Q3P2) = 1 THEN 1 when MAX(Q3P2) > 1 THEN 0 ELSE .S END) AS OWNS_HOUSE LABEL='OWN HOME OR NOT'
	
	FROM SASPDATA.HOUSING1_S
	GROUP BY ID;
QUIT;


PROC PRINT DATA=SASPDATA.HOUSING2 (OBS)=10;RUN;


PROC MEANS DATA = SASPDATA.HOUSING2 NMISS N MIN MEAN MEDIAN MAX STD ;
RUN;

/*CREATING A LIBRARY FOR STORING FORMATS*/
/* libname prjformt '/folders/myfolders/formats'; */
/*OPTIONS FMTSEARCH=(PRJFRMT.fm1  WORK); *Specifying the order of Libraries; */
	

PROC FORMAT  LIBRARY=PRJFRMT.fm1;
  VALUE REGION 	  
  		1 = "NORTH PUGET      "
        2 = "WEST BALANCE     "
		3 = "KING             "
		4 = "OTHER PUGET METRO"
		5 = "CLARK            "
		6 = "EAST BALANCE     "
		7 = "SPOKANE          "
		8 = "TRI-CITIES       "
				   ;
  VALUE  AgeSeg
		0 	- <20 	=	'Age: <20    ' 
		20	- <30 	=	'Age: 21--30 '
		30  - <40   = 	'Age: 31--40 '
		40	- <50   = 	'Age: 41--50 '
		50  - <60   = 	'Age: 51--60 '
		60	- HIGH 	= 	'Age: >60    '
		.			= 	'Age: MIssing'
		;	
 
	VALUE  RESIDENCETYPE
 	 	1 = 'OWNERS '
 	 	2 = "RENTERS"
 	 	3 = "NEITHER"
 	 	. = "MIA"
 	 ;
 	 
 	 VALUE  OWNERSORNOT
 	 	1 = 'OWNERS '
 	 	0 = "NOT OWNERS"
 	 ;

RUN;

PROC CONTENTS DATA=SASPDATA.HOUSING2;RUN;

/*UNIVARIATE ANALYSIS*/
TITLE  "HISTOGRAM OF AGE";
PROC SGPLOT DATA=SASPDATA.HOUSING2;
	HISTOGRAM AVG_AGE  /	
	DATASKIN = MATTE;
	RUN;
QUIT;

TITLE  "HOUSE HOLD INCOME";
PROC SGPLOT DATA=SASPDATA.HOUSING;
	HISTOGRAM HHINC /
	DATASKIN = MATTE;
	DENSITY HHINC;
	RUN;
QUIT;


/* AGE , HOUSEHOLD_INCOME */



/* BIVARIATE ANALYSIS*/
/*REGION & HOUSE OWNERS*/

PROC SORT DATA=SASPDATA.HOUSING2 OUT =SASPDATA.HOUSING2S_REGION;
	BY REGION;
RUN;
PROC FREQ DATA=SASPDATA.HOUSING2S_REGION;
	BY REGION;
	TABLE Q3P2_SUM /NOCOL NOCUM NOFREQ ;
RUN;
/*POTTING*/
TITLE  "HOUSE OWNERS - REGION WISE";
PROC SGPLOT DATA=SASPDATA.HOUSING2S_REGION;
	VBAR REGION /GROUP= Q3P2_SUM 
	DATASKIN = MATTE;
	FORMAT REGION REGION.;
	RUN;
QUIT;
TITLE  "";


TITLE  "HOUSE OWNERS OR RENTERS";
PROC SGPLOT DATA=SASPDATA.HOUSING2S_REGION;
	HISTOGRAM Q3P2_SUM
	/DATASKIN = MATTE BINWIDTH=0.5 BINSTART=0 fill;
 	XAXIS VALUES=(-1 to 3 by 1) COLORBANDS=EVEN;
 	FORMAT Q3P2_SUM OWNERS.;
 	RUN;
QUIT;
/* CHI SQUARE TESTS*/
PROC FREQ DATA=SASPDATA.HOUSING2S_REGION;
	TABLE PEOPL*Q3P2_SUM / CHISQ PLOTS = FREQPLOT();
RUN;

PROC FREQ DATA=SASPDATA.HOUSING2S_REGION(DROP=ID);
	TABLE OTHR_INCM_SRC*Q3P2_SUM / CHISQ PLOTS = FREQPLOT();
RUN;

PROC FREQ DATA=SASPDATA.HOUSING2S_REGION(DROP=ID);
	TABLE CHLDRN_LT_20*Q3P2_SUM / CHISQ PLOTS = FREQPLOT();
RUN;

proc corr data= SASPDATA.HOUSING2S_REGION(DROP=ID) plots(maxpoints=50000);
var _All_;
run;

/*1.
/*distribution of people vs hhldincoming*/


/*distribution more people vs hhldincoming*/

	

