LIBNAME HOUSING 'DOWNLOADS';

PROC PRINT DATA = HOUSING.HOUSING2_NOOUT(OBS=5);
RUN;
/* SPLITTING THE DATASET */
PROC SORT DATA = HOUSING.HOUSING2_NOOUT OUT =HOUSING_SORTED;
BY TARGET;
RUN;
PROC SURVEYSELECT DATA = HOUSING_SORTED OUT = HOUSING_SURVEY OUTALL
SAMPRATE = 0.7 SEED = 12345;
STRATA TARGET;
RUN;

*VERIFY CORRECT DATASET;
PROC FREQ DATA = HOUSING_SURVEY;
TABLES SELECTED*TARGET;
RUN;

/* CREATING MODEL */
PROC LOGISTIC DATA=HOUSING2_NOOUT DESCENDING;
CLASS LIST OF CATEGORICAL VARIABLES;
MODEL TARGET(EVENT= '1') = ALL THE PREDICTORS /
SELECTION=STEPWISE EXPB STB LACKFIT;
OUTPUT OUT = NEWFILENAME P=NEW;
STORE YOURLIBRARYNAME;
RUN;
